### ISSUE TITLE
Various issues

### ISSUE THREAD

**Issue by sipertruk** [CKNOEP/BananaBar3#4]
Hello, thanks for porting the addon to classic, new features are nice too.
I ran into a few issues and implemented fixes.

First there's a typo in the .toc, extra r character at the beginning.

In BananaBar3.lua line 1687 you're creating a "Frame" using "SecureActionButtonTemplate" but it must be a "CheckButton" instead, it might work with a "Frame" but the UI complaints that there's no OnClick script in the object.

In BananaBar3.lua line 3464, the prefix "BananaBar3:" is missing before "PlayRemove()", causing and error when dragging an icon on an already assigned target, if I remember correctly it was dragging to the player (not the frame, the skin).

**Comment by sipertruk** [comment]
![Capture](https://user-images.githubusercontent.com/7644041/104328497-271a9280-54ec-11eb-923f-ef1456a846e7.JPG)
This happens in combat.
You can't do SetPoint() on a secure frame in combat so the secure API is throwing ADDON_ACTION_BLOCKED.
To fix it you could add "if UnitAffectingCombat("player") then return end" at the beginning of BananaBar3:OnMouseOverlayUpdate() line 2032.

**Comment by sipertruk** [comment]
The same goes for SetAttribute() line 3596 and 3597, it triggers ADDON_ACTION_BLOCKED.

**Comment by sipertruk** [comment]
Changing visibility options in combat trigger ADDON_ACTION_BLOCKED on lines 588 Show() and 590 Hide(). I suppose SecureActionQueue can be used ?
Edit. In Bananabar3Button.lua

**Comment by CKNOEP** [comment]
Hello
It's amazing.
Thank you for your expertise, and your wise gaze.
Do you want to pull a request
