### ISSUE TITLE
WOTLK

### ISSUE THREAD

**Issue by Golempl** [CKNOEP/BananaBar3#5]
Not working ;(

**Comment by CKNOEP** [comment]
I'm sorry, I'm a little behind on processing the WOTLK-induced changes. I focused on 2 new projects. I should be able to release a new release in the next few days. 
thank you for your patience

**Comment by CKNOEP** [comment]
Yes that's right, I'll edit, thank you

**Comment by CKNOEP** [comment]
See last version

**Comment by Golempl** [comment]
Layout is working now. However when I send pet to target with mark, I can't target it by clicking left click on banana mark, it shows mark occupied by 1 but its not targetable. I may need to do more tests in raid env.
